@startuml

package twisk.mondeIG {
    class ArcIG {
        - PointDeControleIG p1
        - PointDeControleIG p2
        - MondeIG monde
        + ArcIG(MondeIG, String, String)
        + PointDeControleIG getP1()
        + PointDeControleIG getP2()
        + String getP1ID()
        + String getP2ID()
        + String toString()
        + boolean equals(Object obj)
    }

    class EtapeIG {
        - int x
        - int y
        - int id
        - int largeur
        - int hauteur
        - String nom
        - boolean isEtree
        - boolean isSortie
        - boolean restrainte
        - List<EtapeIG> successeurs
        - List<EtapeIG> predecesseurs
        - ArrayList<PointDeControleIG> points
        + EtapeIG(String)
        + int getId()
        + void move(int x, int y)
        + String getNom()
        + void setNom(String nom)
        + void setX(int x)
        + void setY(int y)
        + void setEntree(boolean bool)
        + void setSortie(boolean bool)
        + void setLargeur(int l)
        + void setHauteur(int h)
        + void changeHauteur(int hauteurDiff)
        + void resetHauteur()
        + void resetPoints()
        + void getX(int x)
        + void getY(int y)
        + boolean estUneEntree()
        + boolean estUneSortie()
        + abstract boolean estUneActivite()
        + abstract boolean estUnGuichet()
        + int getId()
        + int getLargeur()
        + int getHauteur()
        + PointDeControleIG getPoint(String id)
        + PointDeControleIG getPointByPos(char pos)
        + boolean isRestrainte()
        + void setEntree(boolean)
        + void setSortie(boolean)
        + void setRestrainte(boolean)
        + void ajouterSuccesseur(EtapeIG)
        + void supprimerSuccesseur(EtapeIG)
        + void ajouterPredecesseur(EtapeIG etape)
        + void supprimerPredecesseur(EtapeIG etape)
        + Iterator<PointDeControleIG> iterator()
        + List<EtapeIG> getSuccesseurs()
        + List<EtapeIG> getPredecesseurs()
        + String toString()
    }

    class ActiviteIG extends EtapeIG {
        - int temps
        - int ecartTemps
        + ActiviteIG(String, int, int)
        + int getTemps()
        + int getEcartTemps()
        + void setTemps(int temps)
        + void setEcartTemps(int ecart)
        + boolean isRestrainte()
        + void setRestrainte(boolean restrainte)
        + boolean estUnGuichet()
        + boolean estUneActivite()
        + String toString()
    }

    class GuichetIG extends EtapeIG {
        - int nbJetons
        + GuichetIG(String, int nbJetons)
        + int getNbJetons()
        + void setNbJetons(int nb)
        + boolean estUnGuichet()
        + boolean estUneActivite()
        + boolean estUneSortie()
        + String toString()
    }

    class MondeIG {
        - Map<Integer, EtapeIG> etapes
        - ArrayList<ArcIG> arcs
        - ArrayList<EtapeIG> etapesSelectionnes
        - ArrayList<ArcIG> arcsSelectionnes
        - PointDeControleIG pointMemorise
        - boolean isEnAttente
        - ArrayList<EtapeIG[]> liaisons
        - GestionnaireClients gestionnaireClients
        - MutableBoolean simulationInProgress
        - int nbClients
        + MondeIG()
        + void ajouter(ActiviteIG)
        + void ajouter(GuichetIG)
        + void delete(EtapeIG...)
        + void marquerCommeEntree()
        + void marquerCommeSortie()
        + ArrayList<EtapeIG> getEtapes()
        + ArrayList<EtapeIG> getEntrees()
        + ArrayList<EtapeIG> getSorties()
        + ArrayList<GuichetIG> getGuichets()
        + ArrayList<ActiviteIG> getActivites()
        + void ajouter(String, String) throws ArcException
        + void delete(ArcIG...)
        + void checkArcs(EtapeIG)
        + void refreshArcs()
        + void clickEtape(EtapeIG)
        + void selectionnerEtape(EtapeIG)
        + void deselectionnerEtape(EtapeIG)
        + void clickArc(ArcIG)
        + boolean contains(ArcIG)
        + void selectionnerArc(ArcIG)
        + void deselectionnerArc(ArcIG)
        + void deselectionner()
        + ArrayList<EtapeIG> getEtapesSelectionnes()
        + boolean isGuichetSelectionne()
        + boolean isActiviteSelectionne()
        + ArrayList<ArcIG> getArcsSelectionnes()
        + PointDeControleIG getPointMemorise()
        + void setPointMemorise(PointDeControleIG)
        + boolean isEnAttente()
        + void setEnAttente(boolean)
        + PointDeControleIG getPoint(String)
        + EtapeIG getEtape(int)
        + Iterator<Map.Entry<Integer, EtapeIG>> iterator()
        + Iterator<ArcIG> arcs()
        + void simuler()
        + Set<Map.Entry<Integer, EtapeIG>> entrySet()
        + void updateLiaison()
        + GestionnaireClients getGestionnaireClients()
        + void setGestionnaireClients(GestionnaireClients)
        + boolean isSimulationStopped()
        + void setSimulationInProgress(MutableBoolean)
        + Iterator<EtapeIG[]> iteratorliaison()
        + String toString()
        + void setCorrespondance(CorrespondancesEtapes)
        + boolean estAccessibleDepuis(EtapeIG, EtapeIG)
        + boolean dfs(EtapeIG, EtapeIG, Set<EtapeIG>)
        + void setNbClients(int) throws MondeException
        + int getNbClients()
    }

    class PointDeControleIG {
        - EtapeIG etape
        - String id
        - int x
        - int y
        - boolean isSortie
        - char pos
        + PointDeControleIG(EtapeIG, String)
        + EtapeIG getEtape()
        + String getId()
        + void follow()
        + int getY()
        + int getX()
        + boolean isSortie()
        + void setSortie(boolean sortie)
        + char getPos()
        + String toString()
        + boolean equals(Object obj)
    }

    class SujetObserve {
        - CopyOnWriteArrayList<Observateur> observateurs
        + SujetObserve()
        + void notifierObservateurs()
        + void ajouterObservateur(Observateur obs)
    }

    class SimulationIG {
        - MondeIG monde
        - Monde creerMonde()
        + SimulationIG(MondeIG)
        + void simuler() throws MondeException, ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException
        + void reagir()
    }

    MondeIG --> ArcIG
    MondeIG --> EtapeIG
    MondeIG --> twisk.outils.GestionnaireClients
    MondeIG --> twisk.outils.MutableBoolean
    MondeIG --> PointDeControleIG
    MondeIG --> twisk.outils.CorrespondancesEtapes
    MondeIG --> SujetObserve
    SimulationIG --> MondeIG
    ArcIG --> PointDeControleIG
}

package twisk.monde {
    class Etape {
        - String nom
        - boolean estUneEntree
        - boolean estUneSortie
        - boolean estRestrainte
        - List<Etape> successeurs
        + Etape(String)
        + String getNom()
        + void setNom(String)
        + boolean estUneEntree()
        + boolean estUneSortie()
        + boolean estRestrainte()
        + void setEntree(boolean)
        + void setSortie(boolean)
        + void setRestrainte(boolean)
        + void ajouterSuccesseur(Etape)
        + List<Etape> getSuccesseurs()
    }

    class Activite extends Etape {
        - int temps
        - int ecartTemps
        + Activite(String, int, int)
        + int getTemps()
        + int getEcartTemps()
    }

    class ActiviteRestreinte extends Activite {
        + ActiviteRestreinte(String, int, int)
    }

    class Guichet extends Etape {
        - int nbJetons
        + Guichet(String, int)
        + int getNbJetons()
    }

    class Monde {
        - List<Etape> etapes
        - List<Etape> entrees
        - List<Etape> sorties
        + Monde()
        + void ajouter(Etape...)
        + void aCommeEntree(Etape)
        + void aCommeSortie(Etape)
        + List<Etape> getEtapes()
        + List<Etape> getEntrees()
        + List<Etape> getSorties()
    }

    class SasEntree extends Activite{
        + SasEntree()
        + boolean estUneEntree()
    }

    class SasSortie extends Activite{
            + SasSortie()
            + boolean estUneSortie()
        }

    Monde --> Etape
    Monde --> CorrespondancesEtapes
}

package twisk.outils {
    class ThreadsManager {
        - static volatile ThreadsManager instance
        - final ArrayList<Thread> threads
        - ThreadsManager()
        + static ThreadsManager getInstance()
        + void lancer(Task<Void> task)
        + void detruireTout()
    }

    class TailleComposants {
        - int clientsW
        - int clientsH
        - int fenetreW
        - int fenetreH
        - int activiteW
        - int activiteH
        - int guichetW
        - int guichetH
        - int gridW
        - int gridH
        + TailleComposants()
        + static TailleComposants getInstance()
        + int getClientsW()
        + int getClientsH()
        + int getFenetreW()
        + int getFenetreH()
        + int getGuichetH()
        + int getGuichetW()
        + int getGridW()
        + int getGridH()
        + int getActiviteH()
        + int getActiviteW()
    }

    class ClassLoaderPerso {
          + ClassLoaderPerso(ClassLoader parent)
          + Class<?> loadClass(String name)
          + Class<?> getClass(String name)
          - byte[] loadClassData(String name)
    }

    class FabriqueIdentifiant {
        - FabriqueIdentifiant()
        + static FabriqueIdentifiant getInstance()
        + int getNumeroEtape()
        + void reset()
    }

    class CorrespondancesEtapes {
            - Map<EtapeIG, Etape> correspondance
            + CorrespondancesEtapes()
            + void ajouter(EtapeIG, Etape)
            + Etape getEtape(EtapeIG)
    }

    class KitC {
        + void creerEnvironnement()
        + void creerFichier(String codeC)
        + void compiler()
        + void construireLaBibliotheque()
        + void killSimulation(GestionnaireClients clients)
    }

    class FabriqueNumero {
        - int compteur
        + FabriqueNumero getInstance()
        + int getNumeroEtape()
        + void reset()
    }

    class MutableBoolean {
        - boolean value
        + MutableBoolean()
        + MutableBoolean(boolean)
        + boolean get()
        + void set(boolean)
    }

    FabriqueNumero --> twisk.simulation.GestionnaireClients
    ThreadsManager --> twisk.mondeIG.SimulationIg
}

package twisk.simulation {
    class Client {
        - int numeroClient
        - int rang
        - boolean aReussi
        + Client(int)
        + int getNumeroClient()
        + int getRang()
        + void incrementerRang()
        + boolean aReussi()
        + void setReussi()
    }

    class GestionnaireClients {
            - List<Client> clients
            + GestionnaireClients()
            + void setClients(int, Etape...)
            + List<Client> getClients()
            + int getClientPosition(Client)
            + int getClientPosition(int)
            + Etape getClientEtape(Client)
        }

    class Simulation {
        - int nbClients
        - Monde monde
        - GestionnaireClients gestionnaireClients
        - List<Observateur> observateurs
        - boolean simulationInProgress
        + Simulation()
        + void setNbClients(int)
        + void ajouterObservateur(Observateur)
        + void notifierObservateurs()
        + void simuler(Monde) throws MondeException
        + void arreterSimulation()
        + boolean isSimulationInProgress()
        + void setSimulationInProgress(boolean)
    }

    interface Observateur {
        + void reagir()
    }

    Simulation --> Monde
    Simulation --> GestionnaireClients
    Simulation --> Observateur
    Simulation --> MutableBoolean
    Simulation --> KitC
    Simulation --> FabriqueIdentifiant
    Simulation --> ClassLoaderPerso
    GestionnaireClients --> Client
}

package twisk.exceptions {
    class MondeException extends Exception {
        + MondeException(String)
    }

    class ArcException extends Exception {
        + ArcException(String)
    }

    class JetonsExeption extends Exception {
        + JetonsExeption(String errorMessage)
    }

    class TempsExeption extends Exception {
        + TempsExeption(String errorMessage)
    }

    class TwiskExeption extends Exception {
        + TwiskExeption(String errorMessage)
    }
}

@enduml
